version: '3.8'

services:
  service1:
    build: ./service_1
    container_name: service1
    ports:
      - "8001:8001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001"]
      interval: 10s
      timeout: 5s
      retries: 3

  service2:
    build:
      context: ./service_2
    ports:
      - "8002:8002"
